#!/usr/bin/env python
"""sc-githooks - The Git pre-receive hook to validate commits

Copyright (c) 2021 Scott Lau
Portions Copyright (c) 2021 InnoGames GmbH
Portions Copyright (c) 2021 Emre Hasegeli
"""
# NOTE: This binary is provided for convenience.  It is nice to be able to run
# the checks from the repository.  This is not included on the releases.  We
# are using entry_points mechanism on the setup.py.

from sys import exit

from githooks.pre_receive import main

exit(main())
